version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=Ina
      - MYSQL_DATABASE=inazaoui
      - MYSQL_ROOT_PASSWORD=password