version: '3'
services:
  mysql:
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=Ina
      - MYSQL_DATABASE=oc
      - MYSQL_ROOT_PASSWORD=password